/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.30.1.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

export interface InstantiateMsg {}
export type ExecuteMsg = {
  receive: Cw20ReceiveMsg;
} | {
  limit_order: {
    market_id: number;
    order_side: OrderSide;
    price: Decimal;
  };
} | {
  market_order: {
    market_id: number;
  };
} | {
  admin: AdminExecuteMsg;
};
export type Uint128 = string;
export type Binary = string;
export type OrderSide = "buy" | "sell";
export type Decimal = string;
export type AdminExecuteMsg = {
  update_admin: {
    new_admin: string;
  };
} | {
  add_market: {
    base_currency: CurrencyInfo;
    quote_currency: CurrencyInfo;
  };
};
export type CurrencyInfo = {
  native: {
    denom: string;
  };
} | {
  cw20: {
    address: string;
  };
};
export interface Cw20ReceiveMsg {
  amount: Uint128;
  msg: Binary;
  sender: string;
}
export type QueryMsg = {
  get_admin: {};
} | {
  get_user_bids: {
    target_market?: number | null;
  };
} | {
  get_user_asks: {
    target_market?: number | null;
  };
};
export type Addr = string;
export interface GetAdminResponse {
  admin?: Addr | null;
}
export interface GetUserAsks {
  orders: UserOrder[];
}
export interface UserOrder {
  market_id: number;
  price: Decimal;
  quantity: Uint128;
}
export interface GetUserBids {
  orders: UserOrder[];
}