/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.30.1.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

export interface InstantiateMsg {}
export type ExecuteMsg = {
  receive: Cw20ReceiveMsg;
} | {
  limit_order: {
    market_id: number;
    price: Decimal;
  };
} | {
  market_order: {
    market_id: number;
  };
} | {
  remove_limit_order: {
    market_id: number;
    price: Decimal;
  };
} | {
  admin: AdminExecuteMsg;
};
export type Uint128 = string;
export type Binary = string;
export type Decimal = string;
export type AdminExecuteMsg = {
  update_admin: {
    new_admin: string;
  };
} | {
  add_market: {
    base_currency: CurrencyInfo;
    quote_currency: CurrencyInfo;
  };
};
export type CurrencyInfo = {
  native: {
    denom: string;
  };
} | {
  cw20: {
    address: string;
  };
};
export interface Cw20ReceiveMsg {
  amount: Uint128;
  msg: Binary;
  sender: string;
}
export type QueryMsg = {
  get_admin: {};
} | {
  get_markets: {};
} | {
  get_user_bids: {
    target_market?: number | null;
    user_address: Addr;
  };
} | {
  get_user_asks: {
    target_market?: number | null;
    user_address: Addr;
  };
} | {
  get_user_orders: {
    target_market?: number | null;
    user_address: Addr;
  };
} | {
  get_market_book: {
    market_id: number;
    nb_levels: number;
  };
};
export type Addr = string;
export interface GetAdminResponse {
  admin?: Addr | null;
}
export type Uint256 = string;
export interface GetMarketBookResponse {
  asks: BookLevel[];
  bids: BookLevel[];
}
export interface BookLevel {
  price: Decimal;
  quantity: Uint256;
}
export interface GetMarketsResponse {
  markets: SingleMarketInfo[];
}
export interface SingleMarketInfo {
  base_currency: CurrencyInfo;
  market_id: number;
  quote_currency: CurrencyInfo;
}
export type OrderSide = "buy" | "sell";
export interface GetUserAsksResponse {
  orders: UserOrderRecord[];
}
export interface UserOrderRecord {
  market_id: number;
  order_side: OrderSide;
  price: Decimal;
  quantity: Uint128;
}
export interface GetUserBidsResponse {
  orders: UserOrderRecord[];
}
export interface GetUserOrdersResponse {
  orders: UserOrderRecord[];
}